### ISSUE TITLE
Générateur de nom

### ISSUE THREAD

**Issue by Gregory-Hoareau** [Gregory-Hoareau/Remus-app#23]
* Description:
En tant que MJ, je veux avoir accès à un générateur de nom (de personnage, de villes, ...) afin de pouvoir simplifier mon improvisation en cours de la partie et de réduire le temps nécessaire à l'écriture du scénario.

* Critères d'acceptation:
- [x] Je peux générer des noms aléatoire
- [x] Je peux sélectionner un genre que je veux générer (ex: ville, humain, elfe, ...)

* Tests:
- [x] Scénario 1 : 
Initialisation : Je suis un MJ possédant une campagne active.
Action : J'accède à la page de génération de nom.
Résultat Attendu : La page apparaît à mon écran.

- [x] Scénario 2 : 
Initialisation : Je suis un MJ possédant une campagne active.
Action : Je génère un nom en choisissant un genre quelconque. 
Résultat Attendu : Un nom aléatoire apparaît et correspond au genre sélectionné.

**Comment by GraulierBrice** [comment]
[ ] Appuyer sur un nom le met dans le presse papier
